#!/usr/bin/perl -w
use strict;
use DBIx::Password;
use Slash::DB;

my $schema = "
CREATE TABLE journals (
	id int(5) DEFAULT '0' NOT NULL auto_increment,
	uid int(11) DEFAULT '0' NOT NULL,
	date datetime DEFAULT '0000-00-00 00:00:00' NOT NULL,
	article longtext,
	description varchar(80),
	PRIMARY KEY (id),
	KEY uidarticle (uid),
	KEY IDandUID (id,uid)
)
CREATE TABLE journal_friends (
	uid int(11) DEFAULT '0' NOT NULL,
	friend int(11) DEFAULT '0' NOT NULL,
	unique jackandjill (uid,friend)
)
";

my $box = "
";

my $user = $ARGV[0];
exit(0) unless $user;
my $dbh = DBIx::Password->connect($user);
$dbh->do($schema);
my $slashdb = Slash::DB->new($user);
#First we insert ourselves into the user's menu
my $menuitem = {
		menu => 'user',
		label => 'Journal',
		value => '/journal.pl',
		seclev => '0',
		type => 'text'
};

$slashdb->createMenuItem($menuitem);

$menuitem = {
		menu => 'user',
		label => 'Add journal entry',
		value => '/journal.pl?op=add',
		seclev => '0',
		type => 'text'
};

$slashdb->createMenuItem($menuitem);

$block = {
		bid => 'journal_entry',
		description => 'Enter box for a journal entry',
		type => 'eval',
		block => $box
};

my $basedir = $slashdb->getVar('basedir', 'value');
system("cp journal.pl $basedir");

$dbh->disconnect();
