update stories set time = date_add(now(), INTERVAL -2 day) where sid like '%14%';
update stories set time = date_add(now(), INTERVAL -1 day) where sid like '%16%';
update stories set time = now() where sid like '%17%';
update story_heap set time = date_add(now(), INTERVAL -2 day) where sid like '%14%';
update story_heap set time = date_add(now(), INTERVAL -1 day) where sid like '%16%';
update story_heap set time = now() where sid like '%17%';
update discussions set flags = 'hitparade_dirty';
alter table stories modify sid char(20) NOT NULL;
alter table story_heap modify sid char(20) NOT NULL;
alter table story_text modify sid char(20) NOT NULL;
